import type { Href } from "expo-router";
import type { ComposeSeedParams } from "@/data/compose/compose-seed-params";

/**
 * Href builders for the routes the list/sidebar screens navigate to. Route
 * strings live here (one place to update when a route file moves); the
 * builders mirror the web paths in @bb/client-core `route-paths.ts` where the
 * native app has the same surface.
 *
 * Typed routes (`.expo/types/router.d.ts`) are generated by Metro from the
 * `app/` tree, so they lag behind route files that other screens add in the
 * same change and are absent entirely in CI. `untypedHref` is the single
 * place that crosses that boundary; every builder below funnels through it.
 */
type HrefParams = Record<string, string | undefined>;

function untypedHref(pathname: string, params?: HrefParams): Href {
  const definedParams = params
    ? Object.fromEntries(
        Object.entries(params).filter(
          (entry): entry is [string, string] => entry[1] !== undefined,
        ),
      )
    : undefined;
  const href: { pathname: string; params?: Record<string, string> } = {
    pathname,
    ...(definedParams && Object.keys(definedParams).length > 0
      ? { params: definedParams }
      : {}),
  };
  // Typed-route boundary (see the module comment).
  return href as Href;
}

/** The first value of an expo-router search param, trimmed ("" when absent). */
export function firstParam(value: string | string[] | undefined): string {
  const raw = Array.isArray(value) ? value[0] : value;
  return raw?.trim() ?? "";
}

/**
 * A mobile route path that was computed outside the builders (the deep-link
 * resolver's `next` path after adding a server). Same typed-route boundary.
 */
export function rawPathHref(path: string): Href {
  return path as Href;
}

/** Thread detail (`/threads/[id]`; the web also serves `/projects/:p/threads/:t`). */
export function threadHref(threadId: string): Href {
  return untypedHref("/threads/[id]", { id: threadId });
}

export function threadSearchHref(): Href {
  return untypedHref("/threads/search");
}

/** One terminal, full screen (`/threads/[id]/terminal/[terminalId]`). */
export function threadTerminalHref(threadId: string, terminalId: string): Href {
  return untypedHref("/threads/[id]/terminal/[terminalId]", {
    id: threadId,
    terminalId,
  });
}

export function archivedThreadsHref(projectId?: string): Href {
  return untypedHref("/settings/archived", { projectId });
}

export function serverStatusHref(): Href {
  return untypedHref("/settings/server");
}

interface NewThreadHrefParams extends ComposeSeedParams {
  sectionId?: string;
  initialPrompt?: string;
}

/**
 * New thread: home with its bottom composer opened on these params (the
 * home screen reads them from the route). Besides a project / section /
 * initial prompt it accepts the thread seeds from `@/data/compose`
 * `compose-seed-params` (fork, handoff, reuse worktree). Navigate with
 * `router.navigate` so an existing home entry is reused with new params
 * instead of a second one being pushed.
 */
export function newThreadHref(params: NewThreadHrefParams = {}): Href {
  return untypedHref("/", {
    // Opens the dock even with no other params (see HomeScreen).
    newThread: "1",
    projectId: params.projectId,
    sectionId: params.sectionId,
    initialPrompt: params.initialPrompt,
    reuseEnvironmentId: params.reuseEnvironmentId,
    forkSourceThreadId: params.forkSourceThreadId,
    forkSourceSeqEnd: params.forkSourceSeqEnd,
    forkSourceThreadTitle: params.forkSourceThreadTitle,
    handoffSourceThreadId: params.handoffSourceThreadId,
    handoffSourceThreadTitle: params.handoffSourceThreadTitle,
  });
}

/** Project settings (sources add/remove; owned by the project screens). */
export function projectSettingsHref(projectId: string): Href {
  return untypedHref("/projects/[id]/settings", { id: projectId });
}

interface ConnectEnrollHrefParams {
  code?: string;
  serverUrl?: string;
  apex?: string;
  /** Re-pair an existing connect profile (revoked credential). */
  profileId?: string;
}

/** bb connect enrollment (`/connect`; also the `bb://connect?code=…` deep link). */
export function connectEnrollHref(params: ConnectEnrollHrefParams = {}): Href {
  return untypedHref("/connect", {
    code: params.code,
    serverUrl: params.serverUrl,
    apex: params.apex,
    profileId: params.profileId,
  });
}

/** New project flow (owned by the project screens). */
export function newProjectHref(): Href {
  return untypedHref("/projects/new");
}

/**
 * Thread files (`/threads/[id]/files`): the file browser / search when no
 * `params` name a file, otherwise the full-screen file preview (`kind`,
 * `path`, `line`, `source`, `status` from `@/screens/files`
 * `buildFilePreviewRouteParams`).
 */
export function threadFilesHref(
  threadId: string,
  params: Record<string, string | undefined> = {},
): Href {
  return untypedHref("/threads/[id]/files", { id: threadId, ...params });
}

// --- Plugins, marketplaces, skills (Phase 7; owned by @/screens/plugins + extensions)

/** Installed plugins (`/settings/plugins`). */
export function pluginsHref(): Href {
  return untypedHref("/settings/plugins");
}

/** Plugin catalog browse (`/settings/plugins/browse`). */
export function pluginBrowseHref(): Href {
  return untypedHref("/settings/plugins/browse");
}

/** One installed plugin (`/settings/plugins/[pluginId]`; the web path too). */
export function pluginDetailHref(pluginId: string): Href {
  return untypedHref("/settings/plugins/[pluginId]", { pluginId });
}

/** A plugin's log tail (`/settings/plugins/[pluginId]/logs`). */
export function pluginLogsHref(pluginId: string): Href {
  return untypedHref("/settings/plugins/[pluginId]/logs", { pluginId });
}

/** Plugin marketplaces (`/settings/marketplaces`; the web path too). */
export function marketplacesHref(): Href {
  return untypedHref("/settings/marketplaces");
}

/** The skills library (`/settings/skills`). */
export function skillsHref(): Href {
  return untypedHref("/settings/skills");
}

/** One library skill, read-only (`/settings/skills/[skillId]`). */
export function skillDetailHref(skillId: string, projectId?: string): Href {
  return untypedHref("/settings/skills/[skillId]", { skillId, projectId });
}

/** skills.sh registry browse (`/settings/skills/registry`). */
export function registrySkillsHref(): Href {
  return untypedHref("/settings/skills/registry");
}

/** One registry skill (`/settings/skills/registry/[registrySkillId]`). */
export function registrySkillDetailHref(registrySkillId: string): Href {
  return untypedHref("/settings/skills/registry/[registrySkillId]", {
    registrySkillId,
  });
}

// --- Settings, machines, updates (Phase 7; owned by @/screens/settings + machines)

type SettingsSectionRoute =
  | "general"
  | "appearance"
  | "experiments"
  | "usage"
  | "updates";

/** One settings bucket (`/settings/<section>`; the web paths too). */
export function settingsSectionHref(section: SettingsSectionRoute): Href {
  return untypedHref(`/settings/${section}`);
}

export type SettingsProviderRoute = "codex" | "claude-code";

/** A provider's settings page (`/settings/providers/[providerId]`). */
export function providerSettingsHref(providerId: SettingsProviderRoute): Href {
  return untypedHref("/settings/providers/[providerId]", { providerId });
}

/** The machines list (`/settings/machines`). */
export function machinesHref(): Href {
  return untypedHref("/settings/machines");
}

/** One machine (`/settings/machines/[hostId]`; the web path too). */
export function machineDetailHref(hostId: string): Href {
  return untypedHref("/settings/machines/[hostId]", { hostId });
}
