import { Asset } from "expo-asset";
import { File } from "expo-file-system";
import { useEffect, useState } from "react";
import terminalPageAsset from "../../../assets/terminal/index.html";

/**
 * The bundled terminal page (`assets/terminal/index.html`, generated by
 * `scripts/build-terminal-page.ts`) as an HTML string for
 * `WebView source={{ html }}`. Read once per app session.
 */
let cached: Promise<string> | null = null;

function loadTerminalPageHtml(): Promise<string> {
  if (cached === null) {
    cached = (async () => {
      const asset = Asset.fromModule(terminalPageAsset);
      await asset.downloadAsync();
      const uri = asset.localUri ?? asset.uri;
      return new File(uri).text();
    })().catch((error: unknown) => {
      cached = null;
      throw error;
    });
  }
  return cached;
}

interface TerminalPageHtmlState {
  html: string | null;
  error: Error | null;
}

export function useTerminalPageHtml(): TerminalPageHtmlState {
  const [state, setState] = useState<TerminalPageHtmlState>({
    html: null,
    error: null,
  });
  useEffect(() => {
    let cancelled = false;
    loadTerminalPageHtml().then(
      (html) => {
        if (!cancelled) setState({ html, error: null });
      },
      (error: unknown) => {
        if (!cancelled) {
          setState({
            html: null,
            error: error instanceof Error ? error : new Error(String(error)),
          });
        }
      },
    );
    return () => {
      cancelled = true;
    };
  }, []);
  return state;
}
